spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD:admin}
      database: test_database
      port: 27017

server:
  context-path: /uaa
  port: 5000
